import json
import re
from collections.abc import Iterator
from pathlib import Path

import pytest

from roger_api.services.notes_markdown import (
    AiNotesMarkdown,
    NoteBlock,
    render_ai_notes,
    render_markdown,
    split_note_blocks,
)
from roger_api.services.transcript_render import format_offset

# Shared with the editor (M4-T17's citationNode.test.ts) and, from M4-T8 on, regenerated by the
# AI doc builder in notes_generation.py. See the shape in docs/plans/M4-notes-and-ai.md.
FIXTURE = Path(__file__).parent / "fixtures" / "ai_notes_doc.json"

type Json = dict[str, object]


def doc(*content: Json) -> Json:
    return {"type": "doc", "content": list(content)}


def text(value: str, *marks: str | Json) -> Json:
    node: Json = {"type": "text", "text": value}
    if marks:
        node["marks"] = [{"type": mark} if isinstance(mark, str) else mark for mark in marks]
    return node


def inline(*content: str | Json) -> list[Json]:
    return [text(part) if isinstance(part, str) else part for part in content]


def paragraph(*content: str | Json) -> Json:
    return {"type": "paragraph", "content": inline(*content)}


def heading(level: int, *content: str | Json) -> Json:
    return {"type": "heading", "attrs": {"level": level}, "content": inline(*content)}


def item(*content: str | Json) -> Json:
    """A list item. A bare string is its paragraph, as StarterKit requires one first."""
    return {
        "type": "listItem",
        "content": [paragraph(part) if isinstance(part, str) else part for part in content],
    }


def bullets(*items: Json) -> Json:
    return {"type": "bulletList", "content": list(items)}


def ordered(start: int, *items: Json) -> Json:
    return {"type": "orderedList", "attrs": {"start": start}, "content": list(items)}


def citation(start_ms: int, label: str = "", support: str = "ok") -> Json:
    return {
        "type": "citation",
        "attrs": {
            "segmentIds": ["fd9daa6d-24ad-4dec-8fca-01604dd531da"],
            "startMs": start_ms,
            "label": label,
            "support": support,
        },
    }


def link(href: str) -> Json:
    return {"type": "link", "attrs": {"href": href}}


def descendants(node: object) -> Iterator[Json]:
    if isinstance(node, dict):
        yield node
        content = node.get("content")
        if isinstance(content, list):
            for child in content:
                yield from descendants(child)


def test_headings_lists_and_marks_render_as_markdown() -> None:
    notes = doc(
        heading(1, "Weekly sync"),
        paragraph(
            "Shipping is ",
            text("on track", "bold"),
            ", ",
            text("mostly", "italic"),
            "; see ",
            text("the board", link("https://board.example")),
            " and run ",
            text("make check", "code"),
            ". ",
            text("Old plan", "strike"),
            ".",
        ),
        paragraph(),
        heading(3, "Risks"),
        bullets(item("Vendor delay"), item("Hiring", bullets(item("Two roles open")))),
        ordered(3, item("Third"), item("Fourth")),
        {"type": "blockquote", "content": [paragraph("Ship it.")]},
        {"type": "codeBlock", "attrs": {"language": "bash"}, "content": [text("make check")]},
        {"type": "horizontalRule"},
        paragraph("Line one", {"type": "hardBreak"}, "line two"),
    )

    assert render_markdown(notes) == (
        "# Weekly sync\n"
        "\n"
        "Shipping is **on track**, *mostly*; see [the board](https://board.example) and run "
        "`make check`. ~~Old plan~~.\n"
        "\n"
        "### Risks\n"
        "\n"
        "- Vendor delay\n"
        "- Hiring\n"
        "  - Two roles open\n"
        "\n"
        "3. Third\n"
        "4. Fourth\n"
        "\n"
        "> Ship it.\n"
        "\n"
        "```bash\n"
        "make check\n"
        "```\n"
        "\n"
        "---\n"
        "\n"
        "Line one\n"
        "line two"
    )


@pytest.mark.parametrize(
    ("content", "expected"),
    [
        pytest.param(
            [text("on track ", "bold"), text("today")], "**on track** today", id="spaces-outside"
        ),
        pytest.param([text("both", "bold", "italic")], "***both***", id="nested-marks"),
        pytest.param([text("   ", "bold")], "", id="blank-text-gets-no-delimiters"),
        pytest.param([text("a `tick`", "code")], "`` a `tick` ``", id="code-holding-backticks"),
        pytest.param(
            [text("Acme", link("https://acme.example"), "bold")],
            "[**Acme**](https://acme.example)",
            id="link-outermost",
        ),
        pytest.param([text("Acme", {"type": "link", "attrs": {}})], "Acme", id="link-without-href"),
        pytest.param([text("kept", "underline", "highlight")], "kept", id="unknown-marks"),
    ],
)
def test_inline_marks(content: list[Json], expected: str) -> None:
    assert render_markdown(doc({"type": "paragraph", "content": content})) == expected


@pytest.mark.parametrize(
    ("attrs", "expected"),
    [
        pytest.param({"start": 0}, "0. Zero\n1. One", id="zero"),
        pytest.param({}, "1. Zero\n2. One", id="no-start"),
        pytest.param({"start": True}, "1. Zero\n2. One", id="bool-start"),
    ],
)
def test_ordered_list_counts_from_its_start(attrs: Json, expected: str) -> None:
    notes = doc({"type": "orderedList", "attrs": attrs, "content": [item("Zero"), item("One")]})

    assert render_markdown(notes) == expected


def test_hard_break_inside_a_list_item_stays_in_the_item() -> None:
    notes = doc(bullets(item(paragraph("First", {"type": "hardBreak"}, "second")), item("Next")))

    assert render_markdown(notes) == "- First\n  second\n- Next"


def test_citation_nodes_render_as_source_times() -> None:
    notes = doc(
        bullets(
            item(paragraph("Beta ships Friday ", citation(192_000, "03:12"))),
            item(paragraph("Renewal at $50k", citation(305_000), citation(3_725_000))),
        ),
        paragraph("Pasted into my notes ", citation(0), " with text after it"),
    )

    assert render_markdown(notes) == (
        "- Beta ships Friday [00:03:12]\n"
        "- Renewal at $50k [00:05:05] [01:02:05]\n"
        "\n"
        "Pasted into my notes [00:00:00] with text after it"
    )


@pytest.mark.parametrize(
    ("attrs", "expected"),
    [
        pytest.param({"startMs": "192000", "label": "03:12"}, "Said [03:12]", id="string-start"),
        pytest.param({"startMs": True, "label": "03:12"}, "Said [03:12]", id="bool-start"),
        pytest.param({"startMs": -1, "label": "03:12"}, "Said [03:12]", id="negative-start"),
        pytest.param({"label": "03:12"}, "Said [03:12]", id="no-start"),
        pytest.param({}, "Said", id="no-start-no-label"),
    ],
)
def test_citation_without_a_usable_start_falls_back_to_its_label(
    attrs: Json, expected: str
) -> None:
    notes = doc(paragraph("Said ", {"type": "citation", "attrs": attrs}))

    assert render_markdown(notes) == expected


def test_from_your_notes_renders_as_its_own_list() -> None:
    ai_doc = doc(
        heading(2, "Decisions"),
        bullets(item(paragraph("Beta ships Friday ", citation(192_000)))),
        heading(2, "From your notes"),
        paragraph(text("Not said on the call", "italic")),
        bullets(item("Ask about pricing"), item("Check the Q3 budget")),
    )

    assert render_ai_notes(ai_doc) == AiNotesMarkdown(
        notes="## Decisions\n\n- Beta ships Friday [00:03:12]",
        from_your_notes="*Not said on the call*\n\n- Ask about pricing\n- Check the Q3 budget",
    )


def test_from_your_notes_heading_is_found_by_its_words_alone() -> None:
    edited = doc(
        heading(2, "Decisions"),
        bullets(item("Beta ships Friday")),
        heading(3, text("From your ", "bold"), text("Notes", "bold")),
        bullets(item("Ask about pricing")),
    )

    assert render_ai_notes(edited) == AiNotesMarkdown(
        notes="## Decisions\n\n- Beta ships Friday", from_your_notes="- Ask about pricing"
    )


@pytest.mark.parametrize("level", [1, 2])
def test_from_your_notes_ends_at_the_next_heading_at_its_level_or_higher(level: int) -> None:
    # The AI doc is editable, and its end is where a user adds a section. A line copied there with
    # its chip came from the call: read as part of the list, it would say "Not said on the call".
    ai_doc = doc(
        heading(2, "Decisions"),
        bullets(item(paragraph("Beta ships Friday ", citation(192_000)))),
        heading(2, "From your notes"),
        paragraph(text("Not said on the call", "italic")),
        bullets(item("Ask about Q3")),
        heading(3, "Pricing"),
        bullets(item("Ask about seats")),
        heading(level, "Follow-ups"),
        bullets(item(paragraph("Legal signed off ", citation(192_000)))),
    )

    assert render_ai_notes(ai_doc) == AiNotesMarkdown(
        notes=(
            "## Decisions\n\n- Beta ships Friday [00:03:12]\n\n"
            f"{'#' * level} Follow-ups\n\n- Legal signed off [00:03:12]"
        ),
        from_your_notes=(
            "*Not said on the call*\n\n- Ask about Q3\n\n### Pricing\n\n- Ask about seats"
        ),
    )


def test_ai_notes_without_from_your_notes_have_an_empty_list() -> None:
    ai_doc = doc(heading(2, "Decisions"), bullets(item("Beta ships Friday")))

    assert render_ai_notes(ai_doc) == AiNotesMarkdown(
        notes="## Decisions\n\n- Beta ships Friday", from_your_notes=""
    )


def test_unknown_nodes_keep_their_text() -> None:
    notes: Json = {
        "type": "doc",
        "content": [
            {
                "type": "taskList",
                "content": [
                    {"type": "taskItem", "attrs": {"checked": True}, "content": [paragraph("Send")]}
                ],
            },
            paragraph("Ping ", {"type": "smartLink", "content": [text("acme.example")]}, " today"),
            {"type": "callout", "content": [text("Remember the demo", "bold")]},
            {"type": "image", "attrs": {"src": "https://acme.example/logo.png"}},
            {"content": [paragraph("No type at all")]},
            "a stray string",
            42,
        ],
    }

    assert render_markdown(notes) == (
        "Send\n\nPing acme.example today\n\n**Remember the demo**\n\nNo type at all"
    )


def test_unknown_inline_nodes_beside_text_stay_in_its_line() -> None:
    # A mention with text in it, and TipTap's own Mention: an atom with no content at all.
    mention: Json = {"type": "mention", "content": [text("Ann")]}
    atom: Json = {"type": "mention", "attrs": {"id": "u1", "label": "Ann"}}
    notes = doc(
        {"type": "callout", "content": inline("Ping ", mention, " today")},
        {"type": "callout", "content": inline("Call", atom, " back")},
    )

    assert render_markdown(notes) == "Ping Ann today\n\nCall back"
    assert [block.text for block in split_note_blocks(notes)] == ["Ping Ann today", "Call back"]


def test_known_blocks_beside_stray_text_keep_their_own_lines() -> None:
    # Only a hand-made doc mixes text into a list of blocks; the blocks must not fold into it.
    notes = doc(paragraph("One"), text("stray"), heading(2, "Two"))

    assert render_markdown(notes) == "One\n\nstray\n\n## Two"


def test_user_notes_split_into_numbered_blocks() -> None:
    user_doc = doc(
        heading(2, "Pricing"),
        paragraph("They want ", text("annual", "italic"), " billing"),
        paragraph(),
        bullets(item("Discount ask", bullets(item("Maybe 10%"))), item("Send quote")),
        ordered(1, item("Call legal")),
        {"type": "horizontalRule"},
        {"type": "blockquote", "content": [paragraph("Budget is fixed")]},
    )

    assert split_note_blocks(user_doc) == (
        NoteBlock(ref="N1", markdown="## Pricing", text="Pricing"),
        NoteBlock(ref="N2", markdown="They want *annual* billing", text="They want annual billing"),
        NoteBlock(ref="N3", markdown="- Discount ask", text="Discount ask"),
        NoteBlock(ref="N4", markdown="  - Maybe 10%", text="Maybe 10%"),
        NoteBlock(ref="N5", markdown="- Send quote", text="Send quote"),
        NoteBlock(ref="N6", markdown="1. Call legal", text="Call legal"),
        NoteBlock(ref="N7", markdown="> Budget is fixed", text="Budget is fixed"),
    )


# A block's text is what the support check reads as the user's own words and numbers. A link's
# target, a code fence's language and a pasted chip's time are none of those: with them, the URL's
# 75000 backs "deck budget is $75k" and the chip's 12 backs "12 seats", which the user never wrote.
@pytest.mark.parametrize(
    ("block", "markdown", "words"),
    [
        pytest.param(
            paragraph("Deck ", text("budget", link("https://docs.example/d/2024/q3-75000"))),
            "Deck [budget](https://docs.example/d/2024/q3-75000)",
            "Deck budget",
            id="link-target",
        ),
        pytest.param(
            {"type": "codeBlock", "attrs": {"language": "html5"}, "content": [text("x = 1")]},
            "```html5\nx = 1\n```",
            "x = 1",
            id="code-fence-and-language",
        ),
        pytest.param(
            paragraph("Renewal ", citation(725_000)), "Renewal [00:12:05]", "Renewal", id="chip"
        ),
        pytest.param(
            paragraph("Renewal", citation(725_000), "for ten seats"),
            "Renewal [00:12:05] for ten seats",
            "Renewal for ten seats",
            id="chip-between-words",
        ),
        pytest.param(
            paragraph(text("Ship", "bold"), " ", text("now", "strike"), " ", text("v2", "code")),
            "**Ship** ~~now~~ `v2`",
            "Ship now v2",
            id="mark-delimiters",
        ),
    ],
)
def test_note_block_text_is_the_words_alone(block: Json, markdown: str, words: str) -> None:
    assert split_note_blocks(doc(block)) == (NoteBlock(ref="N1", markdown=markdown, text=words),)


def test_empty_user_notes_have_no_blocks() -> None:
    assert split_note_blocks(doc()) == ()
    assert split_note_blocks(doc(paragraph(), bullets(item(paragraph())))) == ()


def test_fixture_doc_renders() -> None:
    fixture = json.loads(FIXTURE.read_text(encoding="utf-8"))

    rendered = render_ai_notes(fixture)

    start_times: list[int] = []
    for node in descendants(fixture):
        if node.get("type") != "citation":
            continue
        attrs = node.get("attrs")
        assert isinstance(attrs, dict)
        # The attrs the builder writes and the editor declares; the renderer reads startMs.
        assert set(attrs) == {"segmentIds", "startMs", "label", "support"}
        assert isinstance(attrs["startMs"], int)
        start_times.append(attrs["startMs"])
    assert start_times
    for start_ms in start_times:
        assert f"[{format_offset(start_ms)}]" in rendered.notes

    source_times = re.compile(r"\[\d{2,}:\d{2}:\d{2}\]")
    ai_bullets = [line for line in rendered.notes.splitlines() if line.startswith("- ")]
    assert ai_bullets
    assert all(re.search(r"\[\d{2,}:\d{2}:\d{2}\]$", line) for line in ai_bullets)
    assert rendered.from_your_notes.startswith("*Not said on the call*\n\n- ")
    assert not source_times.search(rendered.from_your_notes)

    whole = render_markdown(fixture)
    for node in descendants(fixture):
        value = node.get("text")
        if isinstance(value, str) and value.strip():
            assert value.strip() in whole
